CREATE OR REPLACE FUNCTION F_TOTAL_ESTUDIANTES_SIN_PROYECTO
RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_total
    FROM ESTUDIANTE
    WHERE id_proyecto IS NULL;
    RETURN v_total;
END F_TOTAL_ESTUDIANTES_SIN_PROYECTO;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Estudiantes sin proyecto: ' || F_TOTAL_ESTUDIANTES_SIN_PROYECTO);
END;
/
