CREATE OR REPLACE PACKAGE PKG_GESTION_ESTUDIANTES AS

    PROCEDURE P_ASIGNAR_PROYECTO(
        p_rut_estudiante IN ESTUDIANTE.NUMRUN%TYPE,
        p_id_proyecto    IN PROYECTO.ID_PROYECTO%TYPE
    );

    PROCEDURE P_QUITAR_PROYECTO(
        p_rut_estudiante IN ESTUDIANTE.NUMRUN%TYPE
    );

END PKG_GESTION_ESTUDIANTES;
/